name: Run Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    # The service container is used to run MySQL.
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: SECRET
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306

    steps:
      # Checkout the code in the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_sqlite, pdo_mysql
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: php-cs-fixer

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.8.0'

      # Directory Permissions
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # Coping .env
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Install Composer dependencies
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Cache Composer dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # Install Node Dependencies
      - name: Install Dependencies
        run: npm install

      # Cache node modules
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      # Build Assets
      - name: Build Assets
        run: npm run build

      # Generate the application key
      - name: Generate key
        run: php artisan key:generate

      # Create Database
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      # Run migrations
      - name: Run migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate --force

      # Run Unit Tests
      - name: Run Unit Tests
        run: ./vendor/bin/pest tests/Unit

      # Run Feature Tests
      - name: Run Integration Tests
        run: ./vendor/bin/pest tests/Feature
